language: c

addons:
    apt:
        packages:
        - libusb-1.0-0-dev

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libusb-1.0-0-dev

script:
    - make

sudo: required
dist: xenial
